name: Terraform Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4 # 必要に応じてバージョンを指定

      - name: Terraform Init
        run: cd env/dev/ && terraform init

      - name: Terraform Test
        run: cd env/dev/ && terraform test