name: Terraform Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: cd env/dev/ && terraform init

      - name: Terraform Test
        run: |
          cd env/dev/ && terraform test -filter="tests/ec2_module_test.tftest.hcl"
          cd env/dev/ && terraform test -filter="tests/network_unit_test.tftest.hcl"
        env:
          # テスト用の環境変数
          AWS_ACCESS_KEY_ID:  "test"
          AWS_SECRET_ACCESS_KEY: "test"
          AWS_DEFAULT_REGION: "ap-southeast-1"
